---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config: .eslintrc.js
  csslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- "dist/"
